version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
