global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - Infrastructure metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # FusionPact Backend - Application metrics
  - job_name: 'fusionpact-backend'
    static_configs:
      - targets: ['fusionpact-backend.onrender.com']
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    tls_config:
      insecure_skip_verify: true
    relabel_configs:  # FIXED: Changed from metrics_relabel_configs
      - source_labels: [__address__]
        target_label: instance
        replacement: 'fusionpact-backend-production'

  # FusionPact Backend Local (optional)
  - job_name: 'fusionpact-backend-local'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 30s
